export const countryCodes = {
  eu: {
    // EU and EEA countries
    austria: { value: 'AT', display: 'Austria' },
    belgium: { value: 'BE', display: 'Belgium' },
    bulgaria: { value: 'BG', display: 'Bulgaria' },
    croatia: { value: 'HR', display: 'Croatia' },
    cyprus: { value: 'CY', display: 'Cyprus' },
    czechia: { value: 'CZ', display: 'Czechia' },
    denmark: { value: 'DK', display: 'Denmark' },
    estonia: { value: 'EE', display: 'Estonia' },
    finland: { value: 'FI', display: 'Finland' },
    france: { value: 'FR', display: 'France' },
    germany: { value: 'DE', display: 'Germany' },
    greece: { value: 'GR', display: 'Greece' },
    hungary: { value: 'HU', display: 'Hungary' },
    iceland: { value: 'IS', display: 'Iceland' },
    ireland: { value: 'IE', display: 'Ireland' },
    italy: { value: 'IT', display: 'Italy' },
    latvia: { value: 'LV', display: 'Latvia' },
    liechtenstein: { value: 'LI', display: 'Liechtenstein' },
    lithuania: { value: 'LT', display: 'Lithuania' },
    luxembourg: { value: 'LU', display: 'Luxembourg' },
    malta: { value: 'MT', display: 'Malta' },
    netherlands: { value: 'NL', display: 'Netherlands (the)' },
    norway: { value: 'NO', display: 'Norway' },
    poland: { value: 'PL', display: 'Poland' },
    portugal: { value: 'PT', display: 'Portugal' },
    romania: { value: 'RO', display: 'Romania' },
    slovakia: { value: 'SK', display: 'Slovakia' },
    slovenia: { value: 'SI', display: 'Slovenia' },
    spain: { value: 'ES', display: 'Spain' },
    sweden: { value: 'SE', display: 'Sweden' },
    switzerland: { value: 'CH', display: 'Switzerland' },
  },
  row: {
    // Rest of World countries not yet implemented in flows.
    afghanistan: { value: 'AF', display: 'Afghanistan' },
    albania: { value: 'AL', display: 'Albania' },
    algeria: { value: 'DZ', display: 'Algeria' },
    andorra: { value: 'AD', display: 'Andorra' },
    angola: { value: 'AO', display: 'Angola' },
    antiguaAndBarbuda: { value: 'AG', display: 'Antigua and Barbuda' },
    argentina: { value: 'AR', display: 'Argentina' },
    armenia: { value: 'AM', display: 'Armenia' },
    australia: { value: 'AU', display: 'Australia' },
    azerbaijan: { value: 'AZ', display: 'Azerbaijan' },
    bahrain: { value: 'BH', display: 'Bahrain' },
    bangladesh: { value: 'BD', display: 'Bangladesh' },
    barbados: { value: 'BB', display: 'Barbados' },
    belarus: { value: 'BY', display: 'Belarus' },
    belize: { value: 'BZ', display: 'Belize' },
    benin: { value: 'BJ', display: 'Benin' },
    bhutan: { value: 'BT', display: 'Bhutan' },
    bolivia: { value: 'BO', display: 'Bolivia' },
    bosniaAndHerzegovina: { value: 'BA', display: 'Bosnia and Herzegovina' },
    botswana: { value: 'BW', display: 'Botswana' },
    brazil: { value: 'BR', display: 'Brazil' },
    brunei: { value: 'BN', display: 'Brunei' },
    burkinaFaso: { value: 'BF', display: 'Burkina Faso' },
    burundi: { value: 'BI', display: 'Burundi' },
    cambodia: { value: 'KH', display: 'Cambodia' },
    cameroon: { value: 'CM', display: 'Cameroon' },
    canada: { value: 'CA', display: 'Canada' },
    capeVerde: { value: 'CV', display: 'Cape Verde' },
    centralAfricanRepublic: { value: 'CF', display: 'Central African Republic' },
    chad: { value: 'TD', display: 'Chad' },
    chile: { value: 'CL', display: 'Chile' },
    china: { value: 'CN', display: 'China' },
    colombia: { value: 'CO', display: 'Colombia' },
    comoros: { value: 'KM', display: 'Comoros' },
    congo: { value: 'CG', display: 'Congo' },
    congoDemocraticRepublic: { value: 'CD', display: 'Democratic Republic of the Congo' },
    costaRica: { value: 'CR', display: 'Costa Rica' },
    cuba: { value: 'CU', display: 'Cuba' },
    djibouti: { value: 'DJ', display: 'Djibouti' },
    dominica: { value: 'DM', display: 'Dominica' },
    dominicanRepublic: { value: 'DO', display: 'Dominican Republic' },
    eastTimor: { value: 'TL', display: 'East Timor' },
    ecuador: { value: 'EC', display: 'Ecuador' },
    egypt: { value: 'EG', display: 'Egypt' },
    elSalvador: { value: 'SV', display: 'El Salvador' },
    equatorialGuinea: { value: 'GQ', display: 'Equatorial Guinea' },
    eritrea: { value: 'ER', display: 'Eritrea' },
    eswatini: { value: 'SZ', display: 'Eswatini' },
    ethiopia: { value: 'ET', display: 'Ethiopia' },
    fiji: { value: 'FJ', display: 'Fiji' },
    gabon: { value: 'GA', display: 'Gabon' },
    georgia: { value: 'GE', display: 'Georgia' },
    ghana: { value: 'GH', display: 'Ghana' },
    grenada: { value: 'GD', display: 'Grenada' },
    guatemala: { value: 'GT', display: 'Guatemala' },
    guinea: { value: 'GN', display: 'Guinea' },
    guineaBissau: { value: 'GW', display: 'Guinea-Bissau' },
    guyana: { value: 'GY', display: 'Guyana' },
    haiti: { value: 'HT', display: 'Haiti' },
    honduras: { value: 'HN', display: 'Honduras' },
    india: { value: 'IN', display: 'India' },
    indonesia: { value: 'ID', display: 'Indonesia' },
    iran: { value: 'IR', display: 'Iran' },
    iraq: { value: 'IQ', display: 'Iraq' },
    israel: { value: 'IL', display: 'Israel' },
    ivoryCoast: { value: 'CI', display: 'Ivory Coast' },
    jamaica: { value: 'JM', display: 'Jamaica' },
    japan: { value: 'JP', display: 'Japan' },
    jordan: { value: 'JO', display: 'Jordan' },
    kazakhstan: { value: 'KZ', display: 'Kazakhstan' },
    kenya: { value: 'KE', display: 'Kenya' },
    kiribati: { value: 'KI', display: 'Kiribati' },
    kosovo: { value: 'XK', display: 'Kosovo' },
    kuwait: { value: 'KW', display: 'Kuwait' },
    kyrgyzstan: { value: 'KG', display: 'Kyrgyzstan' },
    laos: { value: 'LA', display: 'Laos' },
    lebanon: { value: 'LB', display: 'Lebanon' },
    lesotho: { value: 'LS', display: 'Lesotho' },
    liberia: { value: 'LR', display: 'Liberia' },
    libya: { value: 'LY', display: 'Libya' },
    madagascar: { value: 'MG', display: 'Madagascar' },
    malawi: { value: 'MW', display: 'Malawi' },
    malaysia: { value: 'MY', display: 'Malaysia' },
    maldives: { value: 'MV', display: 'Maldives' },
    mali: { value: 'ML', display: 'Mali' },
    marshallIslands: { value: 'MH', display: 'Marshall Islands' },
    mauritania: { value: 'MR', display: 'Mauritania' },
    mauritius: { value: 'MU', display: 'Mauritius' },
    mexico: { value: 'MX', display: 'Mexico' },
    federatedStatesOfMicronesia: { value: 'FM', display: 'Federated States of Micronesia' },
    moldova: { value: 'MD', display: 'Moldova' },
    monaco: { value: 'MC', display: 'Monaco' },
    mongolia: { value: 'MN', display: 'Mongolia' },
    montenegro: { value: 'ME', display: 'Montenegro' },
    morocco: { value: 'MA', display: 'Morocco' },
    mozambique: { value: 'MZ', display: 'Mozambique' },
    myanmarBurma: { value: 'MM', display: 'Myanmar (Burma)' },
    namibia: { value: 'NA', display: 'Namibia' },
    nauru: { value: 'NR', display: 'Nauru' },
    nepal: { value: 'NP', display: 'Nepal' },
    newZealand: { value: 'NZ', display: 'New Zealand' },
    nicaragua: { value: 'NI', display: 'Nicaragua' },
    niger: { value: 'NE', display: 'Niger' },
    nigeria: { value: 'NG', display: 'Nigeria' },
    northKorea: { value: 'KP', display: 'North Korea' },
    northMacedonia: { value: 'MK', display: 'North Macedonia' },
    oman: { value: 'OM', display: 'Oman' },
    pakistan: { value: 'PK', display: 'Pakistan' },
    palau: { value: 'PW', display: 'Palau' },
    panama: { value: 'PA', display: 'Panama' },
    papuaNewGuinea: { value: 'PG', display: 'Papua New Guinea' },
    paraguay: { value: 'PY', display: 'Paraguay' },
    peru: { value: 'PE', display: 'Peru' },
    philippines: { value: 'PH', display: 'Philippines' },
    qatar: { value: 'QA', display: 'Qatar' },
    russia: { value: 'RU', display: 'Russia' },
    rwanda: { value: 'RW', display: 'Rwanda' },
    stKittsAndNevis: { value: 'KN', display: 'St Kitts and Nevis' },
    stLucia: { value: 'LC', display: 'St Lucia' },
    stVincent: { value: 'VC', display: 'St Vincent' },
    samoa: { value: 'WS', display: 'Samoa' },
    sanMarino: { value: 'SM', display: 'San Marino' },
    saoTomeAndPrincipe: { value: 'ST', display: 'Sao Tome and Principe' },
    saudiArabia: { value: 'SA', display: 'Saudi Arabia' },
    senegal: { value: 'SN', display: 'Senegal' },
    serbia: { value: 'RS', display: 'Serbia' },
    seychelles: { value: 'SC', display: 'Seychelles' },
    sierraLeone: { value: 'SL', display: 'Sierra Leone' },
    singapore: { value: 'SG', display: 'Singapore' },
    solomonIslands: { value: 'SB', display: 'Solomon Islands' },
    somalia: { value: 'SO', display: 'Somalia' },
    southAfrica: { value: 'ZA', display: 'South Africa' },
    southKorea: { value: 'KR', display: 'South Korea' },
    southSudan: { value: 'SS', display: 'South Sudan' },
    sriLanka: { value: 'LK', display: 'Sri Lanka' },
    sudan: { value: 'SD', display: 'Sudan' },
    suriname: { value: 'SR', display: 'Suriname' },
    syria: { value: 'SY', display: 'Syria' },
    tajikistan: { value: 'TJ', display: 'Tajikistan' },
    tanzania: { value: 'TZ', display: 'Tanzania' },
    thailand: { value: 'TH', display: 'Thailand' },
    theBahamas: { value: 'BS', display: 'The Bahamas' },
    theGambia: { value: 'GM', display: 'The Gambia' },
    togo: { value: 'TG', display: 'Togo' },
    tonga: { value: 'TO', display: 'Tonga' },
    trinidadAndTobago: { value: 'TT', display: 'Trinidad and Tobago' },
    tunisia: { value: 'TN', display: 'Tunisia' },
    turkey: { value: 'TR', display: 'Turkey' },
    turkmenistan: { value: 'TM', display: 'Turkmenistan' },
    tuvalu: { value: 'TV', display: 'Tuvalu' },
    uganda: { value: 'UG', display: 'Uganda' },
    ukraine: { value: 'UA', display: 'Ukraine' },
    unitedArabEmirates: { value: 'AE', display: 'United Arab Emirates' },
    unitedKingdom: { value: 'GB', display: 'United Kingdom' },
    unitedStates: { value: 'US', display: 'United States' },
    uruguay: { value: 'UY', display: 'Uruguay' },
    uzbekistan: { value: 'UZ', display: 'Uzbekistan' },
    vanuatu: { value: 'VU', display: 'Vanuatu' },
    vaticanCity: { value: 'VA', display: 'Vatican City' },
    venezuela: { value: 'VE', display: 'Venezuela' },
    vietnam: { value: 'VN', display: 'Vietnam' },
    yemen: { value: 'YE', display: 'Yemen' },
    zambia: { value: 'ZM', display: 'Zambia' },
    zimbabwe: { value: 'ZW', display: 'Zimbabwe' },
  },
} as const;

export type CountryCode = (typeof countryCodes.eu)[keyof typeof countryCodes.eu] | (typeof countryCodes.row)[keyof typeof countryCodes.row];

export type EuCountryCode = (typeof countryCodes.eu)[keyof typeof countryCodes.eu];

export type RowCountryCode = (typeof countryCodes.row)[keyof typeof countryCodes.row];
